#if (!require("BiocManager", quietly = TRUE))
 # install.packages("Homo.sapiens")
#BiocManager::install("EnhancedVolcano");
#source("https://horvath.genetics.ucla.edu/html/CoexpressionNetwork/GeneAnnotation/installAnRichment.R");
#installAnRichment();
library(WGCNA)
library(tidyverse)
library(dplyr)
library(DESeq2)
library(edgeR)
library(tximport)
library(GenomicFeatures)
library(tximeta)
library(ASpli)
library(biomaRt)
library(data.table)
library(plotly)
library(RColorBrewer)
library(ggplot2)
library(data.table)
library(cluster)
library(genefilter)
library(umap)
library(impute)
library(ggforce)
library(limma)
library(org.Hs.eg.db)
library(knitr)
library(reshape2)
library(gplots)
library(plyr)
library(statmod)
library(MOFA2)
library(factoextra)
library(pheatmap)
library(apeglm)
library(EnhancedVolcano)
library(umap)
library(vcfR)
library(adegenet)
library(glmmTMB)
library(trainomeHelper)
library(trainomeMetaData)



#listEnsembl()



